server:
  port: 9010
spring:
  application:
    name: gateway
  profiles:
    active: @activatedProperties@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-edu
          # lb://nacos中注册的名字
          uri: lb://service-edu
          # path后面是个路由
          predicates: Path=/edu/**
        - id: service-cms
          # lb://nacos中注册的名字
          uri: lb://service-cms
          predicates: Path=/cms/**
        - id: service-msm
          uri: lb://service-msm
          predicates: Path=/msm/**
        - id: service-oss
          uri: lb://service-oss
          predicates: Path=/fileOssService/**
        - id: service-ucenter
          uri: lb://service-ucenter
          predicates: Path=/ucenter/**
