server:
  port: 8001

spring:
  application:
    name: service-edu
  profiles:
    active: @activatedProperties@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis-plus:
  type-aliases-package: com.yzz
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: /mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
#开启熔断
feign:
  hystrix:
    enabled: true

ali_OSS:
  endpoint: oss-cn-beijing.aliyuncs.com
  bucketName: onlineeducationyzz
  AccessKeyId: LTAI4FzEu4ciY3naYFUtddqg
  AccessKeySecret: E7UesWNqUEP8RJKu4SwR5UMwXJuFo2
