#server:
#  port: 8001
#spring:
#  profiles: dev
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.160.4:3306/db1?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#    username: root
#    password: rootroot
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.160.4:8848
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#
#mybatis-plus:
#  type-aliases-package: com.yzz
#  #  configuration:
#  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: /mapper/*.xml
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
##开启熔断
#feign:
#  hystrix:
#    enabled: true