server:
  port: 8005

spring:
  profiles:
    active: @activatedProperties@
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启
  application:
    name: service-acl

mybatis-plus:
  type-aliases-package: com.yzz.service_acl.entity
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: /mapper/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0